In [2]:
a=[10,20,30]
type(a)

list

In [3]:
import numpy as np

a=np.array(a)
type(a)

numpy.ndarray

In [4]:
d=np.array([1,2,3])
d


array([1, 2, 3])

In [5]:
np.ndim(d)

1

In [6]:
b=np.array([[1,2,3],[4,5,6]])
type(b)
np.ndim(b)

2

In [7]:
c=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[9,10,11]]])
c


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 9, 10, 11]]])

In [8]:
c.shape

(2, 2, 3)

In [9]:
b.shape

(2, 3)

In [10]:
c.size

12

In [11]:
b.size

6

In [12]:
c.dtype

dtype('int64')

In [13]:
a1=np.arange(0,101)
a1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [14]:
a1=np.arange(0,101,2)
a1

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [15]:
#Write the code using np.arange() to get all even numbers between 21 and 70, (70 inclusive)
a1=np.arange(22,71,2)
a1

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60, 62, 64, 66, 68, 70])

In [16]:
#Write the code using np.arange() to get all odd numbers between 20 and 71. (71 inclusive)
a2=np.arange(21,72,2)
a2

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69, 71])

In [17]:
a2.dtype

dtype('int64')

In [18]:
a1=a1.astype("float")

In [19]:
a1.dtype

dtype('float64')

In [20]:
#linspace
b=np.linspace(1,100,5)
b

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [21]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 9, 10, 11]]])

In [22]:
c[1][1][1]

np.int64(10)

In [23]:
c.shape

(2, 2, 3)

In [24]:
c[0,1,0:2]

array([4, 5])

In [25]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 9, 10, 11]]])

In [26]:
c[1,1,1:3]

array([10, 11])

In [27]:
mat=np.arange(1,37)
mat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [28]:
mat=mat.reshape(6,6)
mat

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [29]:
mat[1:4,2:5]

array([[ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23]])

In [30]:
#every 2nd row,2nd col
mat[::2,::2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

In [31]:
#reverse rows without chnaging coluns
mat[:,::-1]

array([[ 6,  5,  4,  3,  2,  1],
       [12, 11, 10,  9,  8,  7],
       [18, 17, 16, 15, 14, 13],
       [24, 23, 22, 21, 20, 19],
       [30, 29, 28, 27, 26, 25],
       [36, 35, 34, 33, 32, 31]])

In [32]:
#middle
mat[2:4,2:4]

array([[15, 16],
       [21, 22]])

In [34]:
#vectorization cannot be done in lists we need loops or function

def fun(l):
    return l*5
l=[1,2,3,4,5]

m=list(map(fun,l))
m

[5, 10, 15, 20, 25]

In [35]:
#vectorization in arrays
la=np.array(l)
print(la*5)

[ 5 10 15 20 25]


In [36]:
#broadcasting

a=[1,2,3]
print(a)
b=[[4],[5],[6]]
print(b)
a+b

[1, 2, 3]
[[4], [5], [6]]


[1, 2, 3, [4], [5], [6]]

In [37]:
a=np.array([1,2,3])
print(a)
b=np.array([[4],[5],[6]])
print(b)
c=a+b
c

[1 2 3]
[[4]
 [5]
 [6]]


array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [38]:
np.ndim(a)

1

In [39]:

np.ndim(b)

2

In [40]:

np.ndim(c)


2

In [41]:

#math fun
c

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [42]:

np.sum(c)

np.int64(63)

In [43]:

np.max(c)

np.int64(9)

In [44]:

np.min(c)

np.int64(5)

In [45]:

np.mean(c)

np.float64(7.0)

In [46]:

np.median(c)

np.float64(7.0)

In [47]:

np.log(c)

array([[1.60943791, 1.79175947, 1.94591015],
       [1.79175947, 1.94591015, 2.07944154],
       [1.94591015, 2.07944154, 2.19722458]])

In [48]:

np.sqrt(c)

array([[2.23606798, 2.44948974, 2.64575131],
       [2.44948974, 2.64575131, 2.82842712],
       [2.64575131, 2.82842712, 3.        ]])

In [49]:

np.exp(c)


array([[ 148.4131591 ,  403.42879349, 1096.63315843],
       [ 403.42879349, 1096.63315843, 2980.95798704],
       [1096.63315843, 2980.95798704, 8103.08392758]])

In [50]:

np.std(c)

np.float64(1.1547005383792515)

In [51]:
c

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [52]:

np.dot(a,b)

array([32])

In [53]:

a@b

array([32])

In [54]:

np.random.rand(4,4)

array([[0.49395944, 0.08209847, 0.11072269, 0.41908611],
       [0.0395084 , 0.10627898, 0.22241524, 0.34617838],
       [0.45874137, 0.24898208, 0.14672811, 0.82598394],
       [0.78521119, 0.7848303 , 0.30134977, 0.21925688]])

In [55]:

np.random.randint(1,1000,5)

array([583, 334, 380, 786, 431], dtype=int32)

In [56]:

np.random.normal(8,2,100)#mean.std,size

array([ 5.46058739,  7.43611538,  8.99045426, 11.29769886,  6.14238911,
        8.71648024,  8.58666352,  8.68611271,  9.03448962, 10.15091178,
        6.48099553,  8.54661688,  7.34483826,  6.19846769, 10.11218721,
        7.45033312,  7.27954089,  6.76894641,  6.93718415,  3.56394409,
        7.93555424, 11.72625753,  7.56995906,  5.74890566,  6.28862887,
        4.02704502, 12.51692058,  8.93837597,  8.1490672 ,  6.17092932,
        8.24945575,  8.23538501,  7.96438441,  6.50583421,  5.6811287 ,
        4.08332617,  5.43340976,  7.8786026 , 10.96010851,  8.53431757,
        6.65605877,  8.71451896, 11.17379019,  8.21956626,  9.60820916,
       11.14108406,  7.95967192,  9.18174102,  7.95127656,  5.1182878 ,
        5.97471582, 10.5624721 ,  6.32943978,  6.95929534,  5.49235468,
        7.98643738,  8.43083728,  5.6398456 ,  8.46442828,  9.27313906,
        5.7470441 ,  6.45449377,  9.8702225 ,  6.32828128,  9.35613332,
        7.03614443,  9.64970811,  8.11030217,  4.9073543 , 10.96

In [57]:

#check if my res has same mean,std
ans=np.array([ 9.00977297,  0.65856103,  5.68066668,  8.55947942,  6.36631923,
        6.27892869,  8.55101171,  8.30440369,  5.00325149,  3.66277591,
        5.36793335,  7.60373521,  9.94507821,  6.83887291,  7.26884692,
        7.47150873,  8.65550872,  6.15051055,  5.30439811,  6.1877364 ,
        7.39669924,  7.4369926 , 10.6495616 ,  8.96941711,  8.21808451,
        9.57382746,  8.36234274,  5.9328308 ,  7.46602527,  9.95667098,
        4.31843863,  9.6803947 ,  6.65323456,  6.62411023,  8.38360806,
        7.88996327,  7.81806241,  5.56123701, 11.25444743,  9.40537858,
       10.31909648,  3.89304879,  6.89204958,  6.06886231,  7.25600754,
        8.28729476,  7.44808685, 10.771968  , 10.49498794,  7.7907104 ,
        6.23878743,  6.71003802,  6.8886789 ,  7.94351817,  8.74499357,
       12.00046126,  5.17652843,  3.55261115, 10.31697155,  9.23753933,
        7.81470143,  5.41070272,  5.10529716,  5.35197441,  9.45807276,
        7.9855475 ,  6.42214009,  7.56512819,  7.84457674,  9.24106476,
        6.39363962,  9.52814952,  8.67753456,  7.33464471,  7.73658223,
        6.38961179,  8.64173264,  6.48432673,  8.5726984 ,  6.32950202,
        9.2373224 ,  7.65587755,  4.8664776 ,  5.34090382,  7.95374847,
        8.65900806,  9.14904021,  6.82820409, 12.43303663,  9.05907616,
       10.59535577, 12.44241231, 10.80154701,  8.79520362,  7.70836769,
        7.2429636 ,  9.20345694,  8.21371442,  7.34305408,  6.99718494])

In [58]:

np.mean(ans)

np.float64(7.692664509299999)

In [59]:

np.std(ans)

np.float64(1.984913734406905)

In [60]:
c

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [61]:

#boolean indexing-- filtering
print(c>7)

[[False False False]
 [False False  True]
 [False  True  True]]


In [62]:
#reshaping transform
print(c.reshape(-1,1)) #ml models input
print(c.reshape(1,-1))

[[5]
 [6]
 [7]
 [6]
 [7]
 [8]
 [7]
 [8]
 [9]]
[[5 6 7 6 7 8 7 8 9]]


In [63]:

c.flatten()

array([5, 6, 7, 6, 7, 8, 7, 8, 9])

In [64]:

c

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [65]:

c.ravel()

array([5, 6, 7, 6, 7, 8, 7, 8, 9])

In [66]:
c

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [67]:

np.vstack(c)

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [68]:

np.hstack(c)

array([5, 6, 7, 6, 7, 8, 7, 8, 9])

In [69]:
c

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [70]:

np.sort(c)

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [71]:

np.hsplit(c,3)

[array([[5],
        [6],
        [7]]),
 array([[6],
        [7],
        [8]]),
 array([[7],
        [8],
        [9]])]

In [72]:

np.vsplit(c,3)

[array([[5, 6, 7]]), array([[6, 7, 8]]), array([[7, 8, 9]])]

In [73]:

np.sum(c,axis=0

_IncompleteInputError: incomplete input (2992213205.py, line 1)